### ISSUE TITLE
there is something wrong with my Xcode?

### ISSUE THREAD

**Issue by heyehao2008** [sascha/Lin-Xcode6#3]
when i download the file and build ，restart Xcode with  error that i can not open Xcode anymore.
so i go to Plug-ins ,remove Lin.xcplugin and Xcode worked again. but i also use this Plug on my macbook's Xcode，it's work well。so i doubt that this Plug is conflict for others.

![2](https://cloud.githubusercontent.com/assets/7590049/6073089/9e1240e6-ade4-11e4-9464-d5b94c023056.png)
![1](https://cloud.githubusercontent.com/assets/7590049/6073090/9ec6890c-ade4-11e4-9ded-7d4f586be87c.png)
![3](https://cloud.githubusercontent.com/assets/7590049/6073106/d5917cb2-ade4-11e4-850e-11b8834d4e44.png)

**Comment by sascha** [comment]
The original author of Lin decided to update his version, so I'm not going to maintain this fork anymore. Pleas take a look at https://github.com/questbeat/Lin/ for the original version.
